server:
  port: 8080

spring:
  application:
    name: Sistema Clientes RV

  # ===== BANCO DE DADOS =====
  datasource:
    url: jdbc:mysql://localhost:3306/clientes_rv_db?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
    username: root
    password: Wellsny321@
    driver-class-name: com.mysql.cj.jdbc.Driver

  # ===== JPA/HIBERNATE =====
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    defer-datasource-initialization: true

# ===== LOGGING =====
logging:
  level:
    app.sistemaclientesrv: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"

---
# ===== PROFILE DESENVOLVIMENTO =====
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/clientes_rv_dev?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
  jpa:
    hibernate:
      ddl-auto: create-drop

---
# ===== PROFILE PRODUÇÃO =====
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/clientes_rv_prod?serverTimezone=UTC&useSSL=true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  logging:
    level:
      app.sistemaclientesrv: INFO
      root: WARN